version: "3"
services:
  db:
    image: postgis/postgis:12-3.0
    environment:
      - POSTGRES_DB=geologic_map
      # This allows connections without a password, which is expedient but insecure...
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "54321:5432"
    expose:
      - 5432
    volumes:
      - db_cluster:/var/lib/postgresql/data
  app:
    build: .
    environment:
      - GEOLOGIC_MAP_CONFIG=/app/docker-assets/docker-map-config.json
    ports:
      - "3006:3006"
    expose:
      - "3006"
volumes:
  db_cluster:
