version: '3'
services:
  db:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_DB=geologic_map
    ports:
      - "54321:5432"
    expose:
      - 5432
  app:
    build: .
    environment:
      - GEOLOGIC_MAP_CONFIG=/app/docker-assets/geologic-map-config.json
    ports:
      - '3006:3006'
    expose:
      - '3006'
