[project]
name = "mapboard.topology-manager"
version = "5.0.0"
description = "A PostGIS-based iterative system for building geologic maps"
authors = [{ name = "Daven Quinn", email = "code@davenquinn.com" }]

# We need to adjust mapboard.database Python compatibility before moving to Python 3.14
requires-python = ">=3.10,<3.14"

readme = "README.md"
license = "Apache-2.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "macrostrat.database>=4.1.1,<5",
    "macrostrat.utils>=1.2.1,<2",
    "typer>=0.12.0,<0.27.0",
    "rich>=13.7.1,<16",
    "python-dotenv>=1.0.1,<2",
    "pytest-profiling>=1.7.0,<2",
    "addict>=2.4.0,<3",
]

[project.scripts]
topo = "mapboard.topology_manager.cli:app"

[dependency-groups]
dev = [
    "isort>=5.13.2,<9",
    "black>=24.3.0,<27",
    "pytest>=8.1.1,<10",
    "shapely>=2.1.2,<3",
]

[tool.uv]
default-groups = "all"

[tool.uv.build-backend]
module-name = ["mapboard"]
module-root = ""
namespace = true

[build-system]
requires = ["uv_build>=0.11.1,<0.12.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
# Ensure that tests only load from the local directory
# (helps when this is included as a submodule)
addopts = "--confcutdir=."
