#!/usr/bin/env python
"""
Update colors for units in the database
"""
from os import path, environ
from subprocess import run
from sqlalchemy import create_engine, MetaData, Table

__dir__ = path.join(environ["PROJECT_DIR"],"versioned","map-display")

engine = create_engine(
        "postgresql://localhost/syrtis")
meta = MetaData(engine)

unit = Table('unit', meta,
        schema='mapping',
        autoload=True)

def get_data():
    fn = path.join(__dir__,'map-colors.txt')
    with open(fn) as f:
        lines = list(f)

    for line in lines:
        _ = line.strip()
        if _.startswith('#'):
            continue
        _ = _.split()
        color = None
        symbol = None
        symbol_color = None
        try:
            uid = _[0]
        except IndexError:
            continue
        try:
            color = _[1]
            symbol = _[2]
            symbol_color = _[3]
        except IndexError:
            pass
        if color == 'transparent':
            color = None
        yield uid, color, symbol, symbol_color

conn = engine.connect()

with conn.begin() as trans:
    for uid,color,symbol,symbol_color in get_data():
        stmt = (unit.update()
                .where(unit.c.id==uid)
                .values(color=color, fgdc_symbol=symbol, symbol_color=symbol_color))
        conn.execute(stmt)
    trans.commit()

#script = path.join(__dir__,"fgdc-colors")
#run(script)
