#!/usr/bin/env zsh
# Arguments: dbname, map-colors file

#!/usr/bin/env zsh
here=$(dirname "$(readlink -f "$0")")
base=${here:h}

source "$here/defs.sh"

topo="$here/topology"

cat "$topo/fixtures"/*.sql \
  | psql $dbname -h $host -v srid=$srid

### Rebuild topology, updating contacts as needed

### Updating topology ###
psql $dbname -h $host -f "$topo/procedures/delete-changed.sql"

### Rebuild topology, updating contacts as needed
$topo/update-contacts $dbname
psql $dbname -h $host -f "$topo/procedures/update-contact-data.sql"

