#!/usr/bin/env zsh
# Arguments: dbname, map-colors file

#!/usr/bin/env zsh
here=$(dirname "$(readlink -f "$0")")

dbname="Naukluft"

topo="$here/topology"

cat $topo/fixtures/*.sql \
    $here/display/fixtures/*.sql \
| psql $dbname

### Rebuild topology, updating contacts as needed

### Updating topology ###
psql $dbname -f "$topo/procedures/delete-changed.sql"

### Rebuild topology, updating contacts as needed
$topo/update-contacts
psql $dbname -f "$topo/procedures/update-contact-data.sql"

#psql $dbname -c "REFRESH MATERIALIZED VIEW map_topology.topology_edges;"
psql $dbname -c "REFRESH MATERIALIZED VIEW mapping.map_face"
