#!/bin/bash

while ! $(psql -h db -p 5432 -U postgres geologic_map > /dev/null 2>&1) ; do
  echo "Waiting for database..."
  sleep 1
done

/app/bin/geologic-map create-tables --all
/app/bin/geologic-map create-demo-units
/app/bin/geologic-map serve
