#!/usr/bin/env zsh
here=$(dirname "$(readlink -f "$0")")

dbname="syrtis"

dn="$here/procedures"

for fn in "$here/fixtures"/*; do
  psql $dbname -f $fn
done

psql $dbname -f "$dn/delete-changed.sql"

#psql -P pager=off $dbname -f "$dn/clean-topology.sql"

### Rebuild topology, updating contacts as needed
$here/update-contacts

psql $dbname -f "$dn/update-contact-data.sql"

#update-colors

if [[ "$1" = '--refresh' ]]; then
psql $dbname -c "REFRESH MATERIALIZED VIEW map_topology.topology_edges;"
fi
