#!/usr/bin/env python

from pathlib import Path
from sqlalchemy import create_engine, text
from sqlalchemy.exc import IntegrityError, InternalError
from sys import argv

engine = create_engine("postgresql:///"+argv[1])

def sql(fn):
    _ = Path(__file__).with_name('procedures')/(fn+'.sql')
    with _.open('r') as f:
        return text(f.read())

# Disables all triggers
engine.execute("SET session_replication_role = replica;")
res = engine.execute(sql('get-contacts-to-update'))

failures = []
for id, in list(res):
    try:
        res = engine.execute(sql('update-contact'),id=id)
        print(id)
    except Exception as err:
        failures.append(id)
        print(err)

s = sql('linework-failures')
engine.execute(s, values=failures)
engine.execute("SET session_replication_role = DEFAULT;")

